version: '3.8'
services:
  nginx:
    container_name: nginx_container
    build: .
    ports:
        - 9000:9000
    tty: true
    links:
        - db

  db:
      container_name: pg_container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: slowplanet
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:


